# Site settings
site: danwt
title: danwt - blog
keywords: danwt, blog, software, concurrency
description: >-
  danwt - personal blog
lang: en-UK
timezone:  Europe/London
repo: https://github.com/danwt/danwt.github.io
#google_verify:      XXX # Put your Google Verification here
google_analytics: G-LQ65HF897P # Put your Google Analytics code
#discus-identifier:  XXX

# Author settings
author:
  name: Daniel Tisdall
  bio: software @ planet earth <br> algorithms | concurrency | correctness | sw eng </br>
  picture: assets/headshot.jpg 
  github: danwt # github username
  #twitter: onepase # twitter username
  #facebook: onepase # facebook username
  #instagram: onepase # instagram username
  #youtube: https://www.youtube.com/channel/UCMmAto-wxBootXN91AzBiDg # youtube username
  linkedin: daniel-tisdall-a3594021b # linkedin username
  #email: your-email@email.com # email adress


# URL settings
url: "http://danwt.github.io" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jemoji
paginate: 24
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false